//
// remote_operations_useful_definitions.h
//
// Code automatically generated by asnparser.
//

#ifndef __REMOTE_OPERATIONS_USEFUL_DEFINITIONS_H
#define __REMOTE_OPERATIONS_USEFUL_DEFINITIONS_H

#include "asn1.h"


#ifndef ACSE_1_DEFINED
#define ACSE_1_DEFINED

#include "Platform.h"

#if defined(_WIN32)
	#include "Platform_WIN32.h"
#elif defined(__VMS)
	#include "Platform_VMS.h"
#elif defined(ALS_VXWORKS)
	#include "Platform_VX.h"
#elif defined(ALS_OS_FAMILY_UNIX)
	#include "Platform_POSIX.h"
#endif

//
// Ensure that ACSE_1_DLL is default unless ACSE_1_STATIC is defined
//
#if defined(_WIN32) && defined(_DLL)
	#if !defined(ACSE_1_DLL) && !defined(ACSE_1_STATIC)
		#define ACSE_1_DLL
	#endif
#endif

#if defined(_MSC_VER)
	#if defined(ACSE_1_DLL)
		#if defined(_DEBUG)
			#define ACSE_1_LIB_SUFFIX "d.lib"
		#else
			#define ACSE_1_LIB_SUFFIX ".lib"
		#endif
	#elif defined(_DLL)
		#if defined(_DEBUG)
			#define ACSE_1_LIB_SUFFIX "mdd.lib"
		#else
			#define ACSE_1_LIB_SUFFIX "md.lib"
		#endif
	#else
		#if defined(_DEBUG)
			#define ACSE_1_LIB_SUFFIX "mtd.lib"
		#else
			#define ACSE_1_LIB_SUFFIX "mt.lib"
		#endif
	#endif
#endif

//
// The following block is the standard way of creating macros which make exporting
// from a DLL simpler. All files within this DLL are compiled with the ACSE_1_EXPORTS
// symbol defined on the command line. this symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see
// ACSE_1_API functions as being imported from a DLL, wheras this DLL sees symbols
// defined with this macro as being exported.
//
#if defined(_WIN32) && defined(ACSE_1_DLL)
	#if defined(ACSE_1_EXPORTS)
		#define ACSE_1_API __declspec(dllexport)
	#else
		#define ACSE_1_API __declspec(dllimport)
	#endif
#endif

#if !defined(ACSE_1_API)
	#define ACSE_1_API
#endif

//
// Automatically link ACSE_1 library.
//
#if defined(_MSC_VER)
	#if !defined(ACSE_1_NO_AUTOMATIC_LIBS) && !defined(ACSE_1_EXPORTS)
		#pragma comment(lib, "ACSE_1" ACSE_1_LIB_SUFFIX)
	#endif
#endif
#endif

namespace Remote_Operations_Useful_Definitions {

} // namespace Remote_Operations_Useful_Definitions

#endif // __REMOTE_OPERATIONS_USEFUL_DEFINITIONS_H

// End of remote_operations_useful_definitions.h
