//
// remote_operations_useful_definitions.cxx
//
// Code automatically generated by asnparser.
//

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "remote_operations_useful_definitions.h"

namespace Remote_Operations_Useful_Definitions{

} // namespace Remote_Operations_Useful_Definitions

// End of remote_operations_useful_definitions.cxx
