//
// remote_operations_information_objects.cxx
//
// Code automatically generated by asnparser.
//

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "remote_operations_information_objects.h"



namespace Remote_Operations_Information_Objects{

OPERATION::info_type::info_type()
{
  m_ArgumentType= NULL;
  m_ResultType= NULL;
  m_Errors= NULL;
  m_Linked= NULL;
}

ERROR::info_type::info_type()
{
  m_ParameterType= NULL;
}

OPERATION_PACKAGE::info_type::info_type()
{
  m_Both= NULL;
  m_Consumer= NULL;
  m_Supplier= NULL;
}

} // namespace Remote_Operations_Information_Objects

// End of remote_operations_information_objects.cxx
