//
// remote_operations_generic_ros_pdus.cxx
//
// Code automatically generated by asnparser.
//

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "remote_operations_generic_ros_pdus.h"

namespace Remote_Operations_Generic_ROS_PDUs{

} // namespace Remote_Operations_Generic_ROS_PDUs

// End of remote_operations_generic_ros_pdus.cxx
